### ISSUE TITLE
macOS  10.12.6 安装报错 reference to 'atomic_uint32_t' is ambiguous

### ISSUE THREAD

**Issue by ccuniverse** [swoole/mysql-proxy#5]
os： macOS 10.12.6
php:7.1.8
swoole:2.0.8

make报错，完整信息如下：

`
c++ -DHAVE_CONFIG_H -g -O2 -o mysql_proxy.so  -fPIC -shared mysql_proxy.cpp  `/usr/local/opt/php71/bin/php-config --includes` -std=c++11 -I"./PHP-X"/include -I`/usr/local/opt/php71/bin/php-config --include-dir`/ext/swoole/include -I`/usr/local/opt/php71/bin/php-config --include-dir`/ext/swoole -l phpx
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:48:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/swoole.h:146:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:13:9: error:
      reference to 'atomic_uint32_t' is ambiguous
typedef atomic_uint32_t  sw_atomic_t;
        ^
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:12:27: note:
      candidate found by name lookup is 'atomic_uint32_t'
typedef volatile uint32_t atomic_uint32_t;
                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:1827:26: note:
      candidate found by name lookup is 'std::__1::atomic_uint32_t'
typedef atomic<uint32_t> atomic_uint32_t;
                         ^
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:48:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/swoole.h:2070:27: error:
      address argument to atomic builtin must be a pointer to integer or pointer
      ('sw_atomic_t *' (aka 'atomic<unsigned int> *') invalid)
        if (*lock == 0 && sw_atomic_cmp_set(lock, 0, 1))
                          ^                 ~~~~
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:15:43: note: expanded
      from macro 'sw_atomic_cmp_set'
#define sw_atomic_cmp_set(lock, old, set) __sync_bool_compare_and_swap(lock, old, set)
                                          ^                            ~~~~
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:48:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/swoole.h:2083:35: error:
      address argument to atomic builtin must be a pointer to integer or pointer
      ('sw_atomic_t *' (aka 'atomic<unsigned int> *') invalid)
                if (*lock == 0 && sw_atomic_cmp_set(lock, 0, 1))
                                  ^                 ~~~~
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:15:43: note: expanded
      from macro 'sw_atomic_cmp_set'
#define sw_atomic_cmp_set(lock, old, set) __sync_bool_compare_and_swap(lock, old, set)
                                          ^                            ~~~~
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:49:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/Server.h:578:17: error: call to
      implicitly-deleted copy constructor of 'sw_atomic_t' (aka 'atomic<unsigned int>')
    sw_atomic_t server_fd = serv->connection_list[fd].from_fd;
                ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:1048:7: note:
      copy constructor of 'atomic<unsigned int>' is implicitly deleted because base class
      '__atomic_base<unsigned int>' has a deleted copy constructor
    : public __atomic_base<_Tp>
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:967:7: note:
      copy constructor of '__atomic_base<unsigned int, true>' is implicitly deleted because
      base class '__atomic_base<unsigned int, false>' has a deleted copy constructor
    : public __atomic_base<_Tp, false>
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:947:5: note:
      '__atomic_base' has been explicitly marked deleted here
    __atomic_base(const __atomic_base&) = delete;
    ^
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:49:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/Server.h:750:15: error:
      address argument to atomic builtin must be a pointer to integer or pointer
      ('sw_atomic_t *' (aka 'atomic<unsigned int> *') invalid)
        key = sw_atomic_fetch_add(&serv->worker_round_id, 1);
              ^                   ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:16:43: note: expanded
      from macro 'sw_atomic_fetch_add'
#define sw_atomic_fetch_add(value, add)   __sync_fetch_and_add(value, add)
                                          ^                    ~~~~~
In file included from mysql_proxy.cpp:42:
In file included from /usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/php_swoole.h:49:
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/Server.h:804:19: error:
      address argument to atomic builtin must be a pointer to integer or pointer
      ('sw_atomic_t *' (aka 'atomic<unsigned int> *') invalid)
            key = sw_atomic_fetch_add(&serv->worker_round_id, 1) % serv->worker_num;
                  ^                   ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/php71/7.1.8_20/include/php/ext/swoole/include/atomic.h:16:43: note: expanded
      from macro 'sw_atomic_fetch_add'
#define sw_atomic_fetch_add(value, add)   __sync_fetch_and_add(value, add)
                                          ^                    ~~~~~
mysql_proxy.cpp:101:39: warning: implicit conversion from 'int' to 'char' changes value from
      251 to -5 [-Wconstant-conversion]
        buffer->str[buffer->length] = 251;
                                    ~ ^~~
mysql_proxy.cpp:108:39: warning: implicit conversion from 'int' to 'char' changes value from
      252 to -4 [-Wconstant-conversion]
        buffer->str[buffer->length] = 252;
                                    ~ ^~~
mysql_proxy.cpp:114:39: warning: implicit conversion from 'int' to 'char' changes value from
      253 to -3 [-Wconstant-conversion]
        buffer->str[buffer->length] = 253;
                                    ~ ^~~
mysql_proxy.cpp:119:39: warning: implicit conversion from 'int' to 'char' changes value from
      254 to -2 [-Wconstant-conversion]
        buffer->str[buffer->length] = 254;
                                    ~ ^~~
mysql_proxy.cpp:846:43: warning: implicit conversion from 'int' to 'char' changes value from
      251 to -5 [-Wconstant-conversion]
        buffer->str[buffer->length - 1] = 251;
                                        ~ ^~~
mysql_proxy.cpp:851:43: warning: implicit conversion from 'int' to 'char' changes value from
      252 to -4 [-Wconstant-conversion]
        buffer->str[buffer->length - 1] = 252;
                                        ~ ^~~
mysql_proxy.cpp:857:43: warning: implicit conversion from 'int' to 'char' changes value from
      253 to -3 [-Wconstant-conversion]
        buffer->str[buffer->length - 1] = 253;
                                        ~ ^~~
mysql_proxy.cpp:862:43: warning: implicit conversion from 'int' to 'char' changes value from
      254 to -2 [-Wconstant-conversion]
        buffer->str[buffer->length - 1] = 254;
                                        ~ ^~~
8 warnings and 6 errors generated.
make: *** [all] Error 1
`

**Comment by GXhua** [comment]
不支持macos
